### ISSUE TITLE
is this normal?

### ISSUE THREAD

**Issue by Dackoson** [ivanyordanovgt/brawl-stars-bot#1]
when i launch the bot  and login the bot moves and shoots but in the cmd it says (The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead)

**Comment by ivanyordanovgt** [comment]
Hey, that's normal, ignore it. That message is an waning from an library called "Pillow". `fromstring()` is an function used for reading data. I have missed to change it to `frombuffer()` as I remember I was copying code from somewhere.
